### ISSUE TITLE
Would be nice to see a possiblity to set the ApplicationVersion and MinimumRequiredVersion?

### ISSUE THREAD

**Issue by Franklin89** [Zoltu/Zoltu.Versioning#16]
Since we are deploying with click onve it would be nice to have a possibility to set these properties with the same version the assemblyinfo will be patsched.

**Comment by MicahZoltu** [comment]
Sorry for the delay in getting back to you.

This project is _very_ near to being end-of-lifed in favor of [`GitTools/GitVersion`](https://github.com/GitTools/GitVersion) since it is more full featured and their upcoming release will allow for a versioning scheme that matches the scheme this project provides, but with additional features.  They call this scheme "Mainline Development" and you can see their docs about it here:
http://gitversion.readthedocs.io/en/latest/reference/mainline-development/
A test that shows this working can be seen here:
https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore.Tests/IntegrationTests/MainlineDevelopmentMode.cs#L112

I believe the Mainline Development feature is in beta now, and will be available in their 4.0 release.  You may want to check with them to see if they have ClickOnce support since I will probably not be committing to this project much more.

That being said, you should be able to just follow the instructions in the second half of this answer to achieve what you want: http://stackoverflow.com/a/26996368/879046  I know it isn't as nice as if the NuGet package did it for you (you have to edit your ClickOnce project file XML), but it should at least make it so you can use this project (or `GitVersion` linked above) without waiting for either to add explicit ClickOnce support.

**Comment by MicahZoltu** [comment]
Closing this issue as won't fix per the above comment.  Sorry!
